# Generated by Django 2.0.4 on 2018-08-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fill_status',
            field=models.BooleanField(default=False),
        ),
    ]
