# Generated by Django 2.0.4 on 2018-08-24 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('websites', '0002_site_fill_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ManyToManyField(related_name='sites', to=settings.AUTH_USER_MODEL),
        ),
    ]
