# Generated by Django 2.0.4 on 2018-05-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetcode',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='signupcode',
            name='code',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='code'),
        ),
    ]
