# Generated by Django 2.0.4 on 2018-05-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='path',
            field=models.CharField(default='a.dat', max_length=30),
            preserve_default=False,
        ),
    ]
