# Generated by Django 2.0.4 on 2018-05-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20180516_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
