# Generated by Django 2.0.4 on 2018-05-31 09:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_pagelink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TyposGrammar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('short_message', models.CharField(max_length=100)),
                ('offset', models.IntegerField()),
                ('sentence', models.TextField()),
                ('length', models.IntegerField()),
                ('message', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Content')),
            ],
        ),
        migrations.AddField(
            model_name='replacement',
            name='typos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.TyposGrammar'),
        ),
    ]
