# Generated by Django 2.0.4 on 2018-06-05 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20180531_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typosgrammar',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Content'),
        ),
    ]
