# Generated by Django 2.0.4 on 2018-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typosgrammar',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typosgrammar',
            name='message',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typosgrammar',
            name='short_message',
            field=models.CharField(max_length=255),
        ),
    ]
