# Generated by Django 2.0.4 on 2018-06-26 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20180615_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='job_uid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='dashboard.Site'),
        ),
    ]
