# Generated by Django 2.0.4 on 2018-07-14 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20180626_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagelink',
            name='job_uid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagelink',
            name='job_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='status',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='status',
            field=models.BooleanField(),
        ),
    ]
