# Generated by Django 2.0.4 on 2018-07-16 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20180714_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.Page'),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='dashboard.Page'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
