# Generated by Django 2.0.4 on 2018-07-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20180716_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='image_job_uid',
            new_name='img_job_uid',
        ),
    ]
