# Generated by Django 2.0.4 on 2018-07-16 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20180716_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='dashboard.Page'),
        ),
        migrations.AlterField(
            model_name='imagelink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='url',
            field=models.CharField(max_length=255, verbose_name='Page Link'),
        ),
    ]
