# Generated by Django 2.0.4 on 2018-07-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20180716_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagelink',
            name='url',
            field=models.CharField(max_length=600, verbose_name='Image Link'),
        ),
        migrations.AlterField(
            model_name='pagelink',
            name='url',
            field=models.CharField(max_length=600, verbose_name='Page Link'),
        ),
    ]
