# Generated by Django 2.0.4 on 2018-07-17 19:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_auto_20180716_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='typos_job_uid',
            new_name='job_uid',
        ),
        migrations.RemoveField(
            model_name='page',
            name='img_job_uid',
        ),
        migrations.RemoveField(
            model_name='page',
            name='link_job_uid',
        ),
        migrations.AddField(
            model_name='imagelink',
            name='job_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagelink',
            name='job_uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
