# Generated by Django 2.0.4 on 2018-07-17 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_auto_20180717_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='path',
        ),
    ]
