# Generated by Django 2.0.4 on 2018-07-24 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_remove_content_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='page',
        ),
        migrations.RemoveField(
            model_name='imagelink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='page',
            name='site',
        ),
        migrations.RemoveField(
            model_name='pagelink',
            name='page',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='typos',
        ),
        migrations.RemoveField(
            model_name='site',
            name='user',
        ),
        migrations.RemoveField(
            model_name='typosgrammar',
            name='content',
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='ImageLink',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='PageLink',
        ),
        migrations.DeleteModel(
            name='Replacement',
        ),
        migrations.DeleteModel(
            name='Site',
        ),
        migrations.DeleteModel(
            name='TyposGrammar',
        ),
    ]
